import { prisma } from '../../config/database';
import { ApprovalStatus } from '@prisma/client';

export async function getAllApprovals(filters: {
  status?: ApprovalStatus;
  approverId?: string;
}) {
  const { status, approverId } = filters;
  const where: any = {};
  if (status) where.status = status;
  if (approverId) where.approverId = approverId;

  const approvals = await prisma.approval.findMany({
    where,
    orderBy: { createdAt: 'desc' },
    include: {
      quotation: {
        include: {
          rfq: true,
          vendor: true
        }
      },
      approver: { select: { id: true, name: true, email: true } }
    }
  });

  return approvals;
}

export async function processApproval(approvalId: string, status: 'APPROVED' | 'REJECTED', remarks: string, actorId: string) {
  if (!remarks || !remarks.trim()) {
    throw new Error('Remarks are required for completing approval step');
  }

  return prisma.$transaction(async (tx) => {
    // 1. Get active approval & details
    const approval = await tx.approval.findUnique({
      where: { id: approvalId },
      include: {
        quotation: {
          include: {
            rfq: true,
            vendor: true
          }
        }
      }
    });

    if (!approval) throw new Error('Approval record not found');
    if (approval.status !== 'PENDING') throw new Error('Approval already processed');

    // 2. Update approval status & remarks
    const updatedApproval = await tx.approval.update({
      where: { id: approvalId },
      data: {
        status,
        remarks,
        actionedAt: new Date()
      }
    });

    const quote = approval.quotation;
    const vendor = quote.vendor;

    if (status === 'APPROVED') {
      // Set quote status to SELECTED/AWARDED
      // (Quote was already SELECTED during comparison desk, but let's make sure it's set)
      await tx.quotation.update({
        where: { id: quote.id },
        data: { status: 'SELECTED' }
      });

      // Update RFQ status to AWARDED
      await tx.rFQ.update({
        where: { id: quote.rfqId },
        data: { status: 'AWARDED' }
      });

      // 3. Generate Purchase Order (PO-YYYY-NNNN)
      const count = await tx.purchaseOrder.count();
      const currentYear = new Date().getFullYear();
      const nextSequence = String(count + 1).padStart(4, '0');
      const poNumber = `PO-${currentYear}-${nextSequence}`;

      const po = await tx.purchaseOrder.create({
        data: {
          approvalId,
          generatedBy: actorId, // Generated by the approving manager / system
          poNumber,
          amount: quote.totalPrice,
          status: 'ISSUED' // Set as issued immediately
        }
      });

      // Notify Procurement Officer Priya and Vendor Vikram
      const procurementOfficers = await tx.user.findMany({ where: { role: 'PROCUREMENT_OFFICER' } });
      for (const off of procurementOfficers) {
        await tx.notification.create({
          data: {
            userId: off.id,
            type: 'PO_GENERATED',
            message: `Purchase Order ${poNumber} generated successfully for "${vendor.companyName}" (Amount: ₹${Number(quote.totalPrice).toLocaleString('en-IN')}).`
          }
        });
      }

      // Find Vendor User account to notify
      const vendorUser = await tx.user.findFirst({
        where: { email: vendor.contactEmail }
      });
      if (vendorUser) {
        await tx.notification.create({
          data: {
            userId: vendorUser.id,
            type: 'PO_GENERATED',
            message: `Purchase Order ${poNumber} has been issued to your portal. Please review and acknowledge.`
          }
        });
      }

      // Log Activity
      await tx.activityLog.create({
        data: {
          actorId,
          entityType: 'APPROVAL',
          entityId: approvalId,
          action: 'Approved Quotation',
          metadata: { poNumber, totalPrice: quote.totalPrice }
        }
      });
    } else {
      // Revert quote to SUBMITTED
      await tx.quotation.update({
        where: { id: quote.id },
        data: { status: 'REJECTED' }
      });

      // Reopen RFQ status to PUBLISHED
      await tx.rFQ.update({
        where: { id: quote.rfqId },
        data: { status: 'PUBLISHED' }
      });

      // Notify Procurement Officer
      const procurementOfficers = await tx.user.findMany({ where: { role: 'PROCUREMENT_OFFICER' } });
      for (const off of procurementOfficers) {
        await tx.notification.create({
          data: {
            userId: off.id,
            type: 'APPROVAL_DONE',
            message: `Award Rejected: Manager declined award recommendation to "${vendor.companyName}". Remarks: "${remarks}".`
          }
        });
      }

      // Log Activity
      await tx.activityLog.create({
        data: {
          actorId,
          entityType: 'APPROVAL',
          entityId: approvalId,
          action: 'Rejected Quotation',
          metadata: { remarks }
        }
      });
    }

    return updatedApproval;
  });
}
export async function getApprovalById(id: string) {
  const approval = await prisma.approval.findUnique({
    where: { id },
    include: {
      quotation: {
        include: {
          rfq: { include: { items: true } },
          vendor: true,
          items: true
        }
      },
      approver: { select: { id: true, name: true, email: true } }
    }
  });
  if (!approval) throw new Error('Approval not found');
  return approval;
}
